import type { Metadata } from 'next';
import { type FC, type ReactNode } from 'react';

import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface LayoutProps {
  children: ReactNode;
}

const Layout: FC<Readonly<LayoutProps>> = ({ children }) => {
  return (
    <html lang="en">
      <body className="bg-base-200 min-h-screen">{children}</body>
    </html>
  );
};

export default Layout;
