import type { Metadata } from 'next';
import { type FC, type ReactNode } from 'react';
import { STORYBLOK } from '@/storyblok/env';
import { StoryblokAutoResize } from '@/storyblok/storyblok-autoresize';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface LayoutProps {
  children: ReactNode;
}

const Layout: FC<Readonly<LayoutProps>> = ({ children }) => {
  return (
    <html lang="en">
      <body>
        <StoryblokAutoResize tool={STORYBLOK.TOOL_NAME} />
        {children}
      </body>
    </html>
  );
};

export default Layout;
